[project]
name = "vidbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.1",
    "google-genai>=1.18.0",
    "gradio-client>=1.10.2",
    "pygments>=2.19.1",
    "requests>=2.32.3",
]
